version: "3.8"

services:
  postgresql:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: os2iot
      POSTGRES_USER: os2iot
      POSTGRES_PASSWORD: toi2so
    volumes:
      - pg-data:/var/lib/postgresql:Z

volumes:
  pg-data:
