kind: Service
apiVersion: v1
metadata:
  name: {{ $.Chart.Name }}-svc
  labels:
    app: {{ $.Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: {{ $.Chart.Name }}