apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v -f docker-compose.yml convert -c -o helm-converted
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: os2iot-postgresql
  name: os2iot-postgresql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v -f docker-compose.yml convert -c -o helm-converted
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: os2iot-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: os2iot
        - name: POSTGRES_PASSWORD
          value: toi2so
        - name: POSTGRES_USER
          value: os2iot
        image: postgis/postgis
        livenessProbe:
          exec:
            command:
            - pg_isready -U os2iot
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: os2iot-postgresql
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
