apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v -f docker-compose.yml convert -c -o helm-converted
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: os2iot-frontend
  name: os2iot-frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v -f docker-compose.yml convert -c -o helm-converted
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: os2iot-frontend
    spec:
      containers:
      - image: os2iot-frontend
        name: os2iot-frontend
        ports:
        - containerPort: 4200
        resources: {}
      restartPolicy: Always
status: {}
