apiVersion: networking.k8s.io/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v -f docker-compose.yml convert -c -o helm-converted
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v -f docker-compose.yml convert -c -o helm-converted
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: root
          image: postgres:9.6-alpine
          name: postgresql
          resources: {}
      restartPolicy: Always
status: {}
