apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-configmap
data: # Remember this contains passwords - might be an idea to use secrets and environment variables instead.
  chirpstack-application-server.toml: |
    # See https://www.chirpstack.io/application-server/install/config/ for a full
    # configuration example and documentation.
    [general]
    log_level=5
    
    [postgresql]
    dsn="postgres://chirpstack_as:chirpstack_as@postgres-svc/chirpstack_as?sslmode=disable"
    
    [redis]
    url="redis://redis-svc:6379"
    
    [application_server.integration.mqtt]
    server="tcp://mosquitto-svc:1883"
    
    [application_server.api]
    bind="0.0.0.0:8001"
    public_host="chirpstack-application-server-svc:8001"
    
    [application_server.external_api]
    bind="0.0.0.0:8080"
    jwt_secret="verysecret"
    # cors_allow_origin="*"
