kind: Service
apiVersion: v1
metadata:
  name: {{ $.Chart.Name }}-svc
  labels:
    app: {{ $.Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-to-ns
      port: 8001
      targetPort: 8001
      protocol: TCP    
    - name: http-join
      port: 8003
      targetPort: 8003
      protocol: TCP
  selector:
    app: {{ $.Chart.Name }}