apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-configmap
data: # Remember this contains passwords - might be an idea to use secrets and environment variables instead.
  chirpstack-gateway-bridge.toml: |
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto-svc:1883"]
    username=""
    password=""

