# Default values for aodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Registry the image comes from
CONTAINER_REGISTRY: postgis

# Image that needs to be used.
DOCKER_IMAGE_NAME: postgis
DOCKER_IMAGE_TAG: latest

DOCKER_IMAGE_PULL_POLICY: IfNotPresent

# How many replicas of the pod?
REPLICAS: 1

# How much revision history should be stored? (can clog up etcd)
REVISION_HISTORY_LIMIT: 3

POSTGRES_DB: os2iot
POSTGRES_USER: os2iot
POSTGRES_PASSWORD: toi2so
