apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ $.Chart.Name }}-virtualservice"
spec:
  hosts:
    - {{ .Values.INGRESS_ADDRESS | default  (printf "%s-%s.%s" .Release.Namespace $.Chart.Name .Values.global.DOMAIN_NAME)}}
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - name: {{ $.Chart.Name }}
      route:
        - destination:
            port:
              number: 8081
            host: "{{ $.Chart.Name }}-clusterip-svc"
          headers:
            response:
              add:
                Cache-Control: no-cache # Telling browsers to not cache our responses.