kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Chart.Name }}
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Chart.Name }}-{{ .Values.DOCKER_IMAGE_TAG }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.REPLICAS }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: {{ .Values.REVISION_HISTORY_LIMIT }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        version: "{{ $.Chart.Name }}-{{ .Values.DOCKER_IMAGE_TAG }}"
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.CONTAINER_REGISTRY }}/{{ .Values.DOCKER_IMAGE_NAME }}:{{ .Values.DOCKER_IMAGE_TAG }}"
          imagePullPolicy: {{ .Values.DOCKER_IMAGE_PULL_POLICY }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 5m
              memory: 128Mi
          env:
            - name: DATABASE_HOSTNAME
              value: os2iot-postgres-svc
            - name: DATABASE_PORT
              value: '5432'
            - name: KAFKA_HOSTNAME
              value: os2iot-kafka-svc
            - name: KAFKA_PORT
              value: '9092'
      restartPolicy: Always
